version: "3.7"

services:

  php:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
 my_db:
    image: mariadb:latest

    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=unmotdepasse
      - MYSQL_DATABASE=wp
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

    ports:
      - "3306:3306"

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=my_db
    ports:
      - 8081:80
    depends_on:
      - my_db

  mailhog:  
    image: mailhog/mailhog
    environment: {}
    ports:
      - 1025:1025
      - 8025:8025
    depends_on:
      - my_db

networks:
  backend:
  frontend:
